"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, ClipboardCheck, FileText, FolderLock, History, ReceiptText, Send, Users } from "lucide-react";
import type { ProjectWorkspaceData } from "@/lib/domain";
import { StatusBadge } from "@/components/ui/status-badge";
import { InvitePanel } from "@/components/projects/invite-panel";
import { ArtifactUploader } from "@/components/projects/artifact-uploader";
import { SubmissionForm } from "@/components/projects/submission-form";
import { ReviewForm } from "@/components/projects/review-form";
import { DecisionForm } from "@/components/projects/decision-form";
import { ReceiptPanel } from "@/components/projects/receipt-panel";
import { EvidenceAssistantPanel } from "@/components/projects/evidence-assistant-panel";
import { ChangeRequestPanel } from "@/components/projects/change-request-panel";
import { VerifiedReceiptUpgrade } from "@/components/projects/verified-receipt-upgrade";

const formatBytes = (bytes: number) => bytes < 1024 ? `${bytes} B` : bytes < 1024 * 1024 ? `${Math.round(bytes / 1024)} KB` : `${(bytes / 1024 / 1024).toFixed(1)} MB`;

export function ProjectWorkspace({ data }: { data: ProjectWorkspaceData }) {
  const [tab, setTab] = useState<"brief" | "people" | "evidence" | "submission" | "review" | "receipt" | "activity">(data.receipt ? "receipt" : data.submission ? "review" : "brief");
  const responseByCriterion = useMemo(() => new Map(data.responses.map((response) => [response.criterion_id, response])), [data.responses]);
  const artifactById = useMemo(() => new Map(data.artifacts.map((artifact) => [artifact.id, artifact])), [data.artifacts]);
  const canUpload = ["client", "builder"].includes(data.currentRole) && !["accepted", "archived"].includes(data.project.status);
  const canSubmitRevision = ["client", "builder"].includes(data.currentRole) && (!data.submission || ["changes_requested", "rejected"].includes(data.submission.status));
  const hasReviewed = data.reviews.some((review) => review.reviewer_id === data.currentUserId);
  const tabs = [
    ["brief", ClipboardCheck, "Brief"], ["people", Users, "People"], ["evidence", FolderLock, "Evidence"], ["submission", Send, "Submission"], ["review", FileText, "Review"], ["receipt", ReceiptText, "Receipt"], ["activity", History, "Activity"]
  ] as const;

  return <main className="page"><div className="container">
    <div className="page-head"><div><Link className="button ghost small" href="/dashboard"><ArrowLeft size={14} /> Dashboard</Link><div className="row wrap" style={{ marginTop: 12 }}><StatusBadge status={data.project.status} /><span className="status">your role: {data.currentRole}</span><span className="status">brief v{data.project.brief_version}</span></div><h1 style={{ fontSize: 46, marginTop: 13 }}>{data.project.title}</h1><p>{data.project.summary}</p></div>{data.project.deadline && <div className="card"><div className="small muted">Deadline</div><strong>{new Date(data.project.deadline).toLocaleDateString()}</strong></div>}</div>
    <div className="workspace"><aside className="sidebar" aria-label="Project sections">{tabs.map(([id, Icon, label]) => <button key={id} className={tab === id ? "active" : ""} onClick={() => setTab(id)}><Icon size={17} />{label}{id === "receipt" && data.receipt && <span aria-label="receipt ready">✓</span>}</button>)}</aside>
      <section className="workspace-main">
        {tab === "brief" && <div className="stack"><div className="card"><h2 style={{ fontSize: 30 }}>What must be delivered</h2><p>{data.project.summary}</p><div className="row wrap"><span className="status">version {data.project.brief_version}</span><span className="status">receipt: {data.project.receipt_visibility === "link" ? "link-verifiable" : "private"}</span></div></div><div className="card"><div className="row between"><div><h2 style={{ fontSize: 28 }}>Acceptance criteria</h2><p className="muted small">These requirements govern the final client decision.</p></div><span className="status">{data.criteria.length} criteria</span></div><div className="criteria-list" style={{ marginTop: 16 }}>{data.criteria.map((criterion, index) => <div className="criteria-item" key={criterion.id}><div className="row between"><strong>{index + 1}. {criterion.title}</strong>{criterion.required ? <span className="status">required</span> : <span className="status">optional</span>}</div>{criterion.description && <p className="muted small">{criterion.description}</p>}</div>)}</div></div><div className="notice">Human authority boundary: automatic checks help organize evidence, but only the client can accept or reject the delivery.</div></div>}

        {tab === "people" && (data.currentRole === "client" ? <InvitePanel projectId={data.project.id} members={data.members} /> : <div className="card"><h2 style={{ fontSize: 28 }}>Project members</h2><div style={{ marginTop: 12 }}>{data.members.map((member) => { const name = member.profile?.display_name || member.profile?.email || "Participant"; return <div className="member" key={member.user_id}><div className="row"><span className="avatar">{name.slice(0, 1).toUpperCase()}</span><div><strong>{name}</strong><div className="small muted">{member.profile?.email}</div></div></div><span className="status">{member.role}</span></div>; })}</div></div>)}

        {tab === "evidence" && <div className="stack">{canUpload && <ArtifactUploader projectId={data.project.id} />}<div className="card"><div className="row between"><div><h2 style={{ fontSize: 28 }}>Private evidence library</h2><p className="muted small">Every file is verified against a browser-computed SHA-256 fingerprint.</p></div><span className="status">{data.artifacts.length} files</span></div>{data.artifacts.length === 0 ? <div className="empty" style={{ marginTop: 16 }}><h3>No evidence files yet</h3><p className="muted">The client or builder can upload PDF, Office, text, JSON, ZIP, or image files.</p></div> : <div className="artifact-list" style={{ marginTop: 16 }}>{data.artifacts.map((artifact) => <div className="artifact-item" key={artifact.id}><div className="row between"><div><h4>{artifact.filename}</h4><div className="small muted">{formatBytes(artifact.size_bytes)} · {artifact.mime_type}</div></div><a className="button secondary small" href={`/api/artifacts/${artifact.id}/download`}>Download</a></div>{artifact.description && <p className="small muted">{artifact.description}</p>}<div className="hash">SHA-256 {artifact.sha256}</div></div>)}</div>}</div></div>}

        {tab === "submission" && <div className="stack">{data.submission && <div className="card"><div className="row between"><div><h2 style={{ fontSize: 28 }}>Latest submission · v{data.submission.version}</h2><p className="muted small">Submitted {new Date(data.submission.submitted_at).toLocaleString()}</p></div><StatusBadge status={data.submission.status} /></div><p><strong>Delivery summary</strong><br />{data.submission.summary}</p><p><strong>Limitations</strong><br />{data.submission.limitations || "None disclosed."}</p><p><strong>AI-use disclosure</strong><br />{data.submission.ai_use_notes || "Not disclosed."}</p></div>}{canSubmitRevision ? <><div className="row between"><div><h2 style={{ fontSize: 30 }}>{data.submission ? "Prepare a revised submission" : "Prepare the delivery package"}</h2><p className="muted">Upload evidence first, then map it to every criterion.</p></div></div>{canUpload && <ArtifactUploader projectId={data.project.id} />}<SubmissionForm projectId={data.project.id} criteria={data.criteria} artifacts={data.artifacts} previousSubmission={data.submission} previousResponses={data.responses} /></> : <div className="notice">The latest package is awaiting or has received a decision. Open the Review section.</div>}</div>}

        {tab === "review" && <div className="stack">{data.submission && <EvidenceAssistantPanel criteria={data.criteria} responses={data.responses} artifacts={data.artifacts} checks={data.checks} limitations={data.submission.limitations} aiUseNotes={data.submission.ai_use_notes} />}<ChangeRequestPanel status={data.project.status} />{!data.submission ? <div className="empty"><h3>No submission to review</h3><p className="muted">The builder must submit a delivery package first.</p></div> : <><div className="card"><div className="row between"><div><h2 style={{ fontSize: 28 }}>Criterion-by-criterion review</h2><p className="muted small">Review the response and open the exact evidence files.</p></div><StatusBadge status={data.submission.status} /></div><div className="criteria-list" style={{ marginTop: 16 }}>{data.criteria.map((criterion, index) => { const response = responseByCriterion.get(criterion.id); return <div className="criteria-item" key={criterion.id}><div className="row between"><strong>{index + 1}. {criterion.title}</strong><StatusBadge status={response?.status ?? "not_met"} /></div><p>{response?.response || "No response."}</p><div className="row wrap">{(response?.artifact_ids ?? []).map((id) => { const artifact = artifactById.get(id); return artifact ? <a className="button secondary small" href={`/api/artifacts/${id}/download`} key={id}>{artifact.filename}</a> : null; })}</div></div>; })}</div></div>
          <div className="card"><h2 style={{ fontSize: 28 }}>Mechanical checks</h2><div className="check-list" style={{ marginTop: 14 }}>{data.checks.map((check) => <div className="check-item" key={check.code}><div className="row between"><strong>{check.label}</strong><StatusBadge status={check.status} /></div><div className="small muted">{check.detail}</div></div>)}</div></div>
          {data.reviews.length > 0 && <div className="card"><h2 style={{ fontSize: 28 }}>Reviewer recommendations</h2><div className="stack" style={{ marginTop: 14 }}>{data.reviews.map((review) => <div className="criteria-item" key={review.id}><div className="row between"><strong>{review.reviewer?.display_name || review.reviewer?.email || "Reviewer"}</strong><StatusBadge status={review.recommendation === "accept" ? "pass" : review.recommendation === "reject" ? "fail" : "warning"} /></div><p>{review.notes}</p><div className="small muted">{new Date(review.created_at).toLocaleString()}</div></div>)}</div></div>}
          {data.submission.status === "submitted" && ["reviewer", "client"].includes(data.currentRole) && !hasReviewed && <ReviewForm submissionId={data.submission.id} />}
          {data.decision ? <div className="card elevated"><div className="row between"><h2 style={{ fontSize: 28 }}>Final client decision</h2><StatusBadge status={data.decision.decision} /></div><p>{data.decision.comment}</p><div className="small muted">Recorded {new Date(data.decision.created_at).toLocaleString()}</div></div> : data.currentRole === "client" && data.submission.status === "submitted" ? <DecisionForm submissionId={data.submission.id} /> : null}
        </>}</div>}

        {tab === "receipt" && <div className="stack"><ReceiptPanel receipt={data.receipt} submissionId={data.submission?.id ?? null} accepted={data.decision?.decision === "accepted"} canRevoke={data.currentRole === "client"} /><VerifiedReceiptUpgrade receipt={data.receipt} /></div>}

        {tab === "activity" && <div className="card"><div className="row between"><div><h2 style={{ fontSize: 28 }}>Activity history</h2><p className="muted small">A chronological record of important project actions.</p></div><span className="status">{data.auditEvents.length} events</span></div>{data.auditEvents.length === 0 ? <div className="empty" style={{ marginTop: 16 }}><p className="muted">No activity has been recorded.</p></div> : <div className="activity-list" style={{ marginTop: 18 }}>{data.auditEvents.map((event) => { const actor = data.members.find((member) => member.user_id === event.actor_id); const actorName = actor?.profile?.display_name || actor?.profile?.email || "System"; const label = event.event_type.replaceAll(".", " "); return <div className="activity-item" key={event.id}><span className="activity-dot" /><div><strong>{label}</strong><div className="small muted">{actorName} · {new Date(event.created_at).toLocaleString()}</div></div></div>; })}</div>}</div>}

      </section>
    </div>
  </div></main>;
}
