import fs from 'node:fs';
import path from 'node:path';
import { ethers } from 'ethers';
const network = process.argv[2] || 'sepolia';
const root = path.resolve(import.meta.dirname, '..', '..');
const artifact = JSON.parse(fs.readFileSync(path.join(root, 'artifacts/contracts/GoalOSSignoffAnchorV1.json'), 'utf8'));
const rpc = process.env.SEPOLIA_RPC_URL || process.env.ETHEREUM_RPC_URL;
const pk = process.env.ANCHOR_DEPLOYER_PRIVATE_KEY;
const owner = process.env.ANCHOR_OWNER_ADDRESS;
const signer = process.env.ANCHOR_SERVICE_SIGNER_ADDRESS;
const salt = process.env.ANCHOR_DEPLOYMENT_SALT || ethers.id(`goalos-signoff-anchor-v1:${network}`);
if (!rpc || !pk || !owner || !signer) throw new Error('Missing SEPOLIA_RPC_URL, ANCHOR_DEPLOYER_PRIVATE_KEY, ANCHOR_OWNER_ADDRESS, or ANCHOR_SERVICE_SIGNER_ADDRESS');
if (network !== 'sepolia' && process.env.ALLOW_MAINNET_DEPLOY !== 'I_UNDERSTAND_THIS_IS_AUDITED_AND_AUTHORIZED') throw new Error('Mainnet deploys are disabled by default. Use Sepolia first.');
const provider = new ethers.JsonRpcProvider(rpc);
const wallet = new ethers.Wallet(pk, provider);
const factory = new ethers.ContractFactory(artifact.abi, artifact.bytecode, wallet);
const contract = await factory.deploy(owner, signer, salt);
await contract.waitForDeployment();
const receipt = await contract.deploymentTransaction().wait();
const record = { status: 'DEPLOYED', network, chainId: Number((await provider.getNetwork()).chainId), address: await contract.getAddress(), transactionHash: receipt.hash, owner, signer, salt, deployedBy: wallet.address, deployedAt: new Date().toISOString() };
fs.mkdirSync(path.join(root, 'deployments'), { recursive: true });
fs.writeFileSync(path.join(root, `deployments/goalos-signoff-anchor-${network}.json`), JSON.stringify(record, null, 2) + '\n');
console.log(JSON.stringify(record, null, 2));
